### ISSUE TITLE
linux run with error

### ISSUE THREAD

**Issue by jiahut** [lbl8603/switch#2]
```
➜ sudo RUST_BACKTRACE=1 /tmp/switch/target/debug/switch-desktop  --token xxx
starting...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 19, kind: Uncategorized, message: "No such device" })', switch/src/tun_device/linux.rs:31:40
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:1791:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:1113:23
   4: switch::tun_device::linux::create_tun
             at ./switch/src/tun_device/linux.rs:31:19
   5: switch::Switch::start_::{{closure}}
             at ./switch/src/lib.rs:145:13
   6: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/zhijia/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/park.rs:283:63
   7: tokio::runtime::coop::with_budget
             at /home/zhijia/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/coop.rs:102:5
   8: tokio::runtime::coop::budget
             at /home/zhijia/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/coop.rs:68:5
   9: tokio::runtime::park::CachedParkThread::block_on
             at /home/zhijia/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/park.rs:283:31
  10: tokio::runtime::context::BlockingRegionGuard::block_on
             at /home/zhijia/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/context.rs:315:13
  11: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/zhijia/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/scheduler/multi_thread/mod.rs:66:9
  12: tokio::runtime::runtime::Runtime::block_on
             at /home/zhijia/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.25.0/src/runtime/runtime.rs:284:45
  13: switch::Switch::start
             at ./switch/src/lib.rs:48:22
  14: switch_desktop::main
             at ./switch-desktop/src/main.rs:78:18
  15: core::ops::function::FnOnce::call_once
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by lbl8603** [comment]
It seems that the creation of tun failed. Can you tell me the specific version number of the system?

**Comment by jiahut** [comment]
```
➜ cat /proc/version
Linux version 6.0.9-arch1-1 (linux@archlinux) (gcc (GCC) 12.2.0, GNU ld (GNU Binutils) 2.39.0) #1 SMP PREEMPT_DYNAMIC Wed, 16 Nov 2022 17:01:17 +0000
```

**Comment by lbl8603** [comment]
Your system may not have a tun device.  Try creating tun device node(https://mjmwired.net/kernel/Documentation/networking/tuntap.txt).

**Comment by Droid-MAX** [comment]
if "/dev/tun" exist, then "mkdir -p /dev/net && ln -s /dev/tun /dev/net/tun"
